server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: inventory_user
    password: inventory_pass
  application:
    name: inventory-service

logging:
  level:
    com.smartfiber.inventory: DEBUG
