server:
  port: 8085

spring:
  application:
    name: smartim-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/smartim_user_db
    username: root
    password: Pa$$w0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: a-string-secret-at-least-256-bits-long
  expiration: 86400000 # 1 day in ms
